const images = {
  A: require('../Assets/images/A.png'),
  B: require('../Assets/images/B.png'),
  C: require('../Assets/images/C.png'),
  D: require('../Assets/images/D.png'),
  E: require('../Assets/images/E.png'),
  F: require('../Assets/images/F.png'),
  G: require('../Assets/images/G.png'),
  H: require('../Assets/images/H.png'),
  I: require('../Assets/images/I.png'),
  J: require('../Assets/images/J.png'),
  K: require('../Assets/images/K.png'),
  L: require('../Assets/images/L.png'),
  M: require('../Assets/images/M.png'),
  N: require('../Assets/images/N.png'),
  O: require('../Assets/images/O.png'),
  P: require('../Assets/images/P.png'),
  Q: require('../Assets/images/Q.png'),
  R: require('../Assets/images/R.png'),
  S: require('../Assets/images/S.png'),
  T: require('../Assets/images/T.png'),
  U: require('../Assets/images/U.png'),
  V: require('../Assets/images/V.png'),
  W: require('../Assets/images/W.png'),
  X: require('../Assets/images/X.png'),
  Y: require('../Assets/images/Y.png'),
  Z: require('../Assets/images/Z.png'),
}

export { images };